@echo off
setlocal EnableDelayedExpansion
title trAIlhead - push changes to GitHub
cd /d "%~dp0"

if not exist ".git\" (
  echo This folder is not connected to GitHub yet. Run setup-local.bat first.
  pause
  exit /b 1
)

for /f "delims=" %%b in ('git rev-parse --abbrev-ref HEAD') do set "BRANCH=%%b"

set "DIFF="
for /f %%f in ('git status --porcelain') do set "DIFF=1"
if not defined DIFF (
  echo No changes to push - your folder matches the last commit.
  pause
  exit /b 0
)

echo Changed files:
git status --short
echo.

echo Optional: a test build catches errors before Vercel sees them.
echo Close the start-local window first if it is running.
choice /c YN /m "Run a test build first"
if errorlevel 2 goto :commit
set "HV_MODE=demo"
call npm run build
if errorlevel 1 (
  echo.
  echo [X] Build failed - fix the errors above. Nothing was pushed.
  pause
  exit /b 1
)

:commit
echo.
set "MSG="
set /p "MSG=Describe your change, e.g. Updated homepage colours: "
if not defined MSG set "MSG=Cosmetic updates"

git add -A

REM Safety net: never commit env or secret files.
REM Allowed: .env.example (placeholders only) and next-env.d.ts (generated by Next.js).
REM No /x or $ here: git output has no CR, so findstr end-of-line matching never fires.
git diff --cached --name-only | findstr /r /i /c:"env" /c:"\.pem" | findstr /v /i /l /c:".env.example" /c:"src/lib/config.ts" /c:"next-env.d.ts" >nul
if not errorlevel 1 (
  echo [X] An env or secrets file was about to be committed. Stopping.
  echo     File^(s^):
  git diff --cached --name-only | findstr /r /i /c:"env" /c:"\.pem" | findstr /v /i /l /c:".env.example" /c:"src/lib/config.ts" /c:"next-env.d.ts"
  git reset -q
  pause
  exit /b 1
)

git commit -q -m "!MSG!"
echo Getting the latest from GitHub...
git pull --rebase origin %BRANCH%
if errorlevel 1 (
  echo.
  echo [X] GitHub has changes that clash with yours. Your commit is saved locally.
  echo     Fix the conflicted files, or run   git rebase --abort   to back out.
  pause
  exit /b 1
)

git push origin %BRANCH%
if errorlevel 1 (
  echo.
  echo [X] Push failed. Check your GitHub sign-in and write access.
  pause
  exit /b 1
)

echo.
echo Done. Pushed to %BRANCH% - Vercel will deploy it in a minute or two.
pause
